package dev.screenshotapi.core.domain.entities

enum class UsageLogAction {
    SCREENSHOT_CREATED,
    SCREENSHOT_COMPLETED,
    SCREENSHOT_FAILED,
    SCREENSHOT_RETRIED,
    CREDITS_DEDUCTED,
    CREDITS_ADDED,
    API_KEY_USED,
    API_KEY_CREATED,
    USER_REGISTERED,
    PLAN_UPGRADED,
    PLAN_CHANGED,
    PAYMENT_PROCESSED,
    EMAIL_SENT
}